sources:
  aims:
    type: postgresql
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    db: "AIMS"
    schema: "public"

  amos:
    type: postgresql
    host: ${DB_HOST}
    port: ${DB_PORT}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    db: "AMOS"
    schema: "public"

target:
  dw:
    type: oracle+oracledb
    host: ${DW_HOST}
    port: ${DW_PORT}
    user: ${DW_USER}
    password: ${DW_PASSWORD}
    sid: "ORABD"